sonar.projectKey=DonytXz_Pokedex-React
sonar.organization=donytxz
sonar.projectName=Pokedex-React
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.jsx,src/**/*.test.js,src/**/*.spec.jsx,src/**/*.spec.js
sonar.exclusions=src/**/*.test.jsx,src/**/*.test.js,src/**/*.spec.jsx,src/**/*.spec.js,src/test/**,dist/**,node_modules/**,coverage/**,playwright-report/**,test-results/**,e2e/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
